image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy


build:
    stage: build
    script:
        - dotnet build

test:
    stage: test
    script:
        - dotnet test

deploy: 
    stage: deploy
    script:
        - c:\scripts\deploy.cmd
    environment:
        - test 
